server:
  port: 10002

dubbo:
  # 配置服务信息
  application:
    name: oomall-gateway
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://127.0.0.1:8848
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: -1

    # 设置超时时间
  consumer:
    timeout: 4000
    check: false

spring:
  application:
    name: oomall-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        # 后台权限 转发到权限网关
        - id: privilege
          uri: http://localhost:10001/
          predicates:
            - Path=/shops/{id}/**,/shops


        # 其他模块路由
        # 用户
        - id: user
          uri: http://localhost:9096/
          predicates:
            - Path=/users,/users/logout
            - Method=PUT,GET
          filters:
            - PrefixPath=/user
            - Auth=authorization

        # 其他模块路由
        # 获取状态 无Token
        - id: userState
          uri: http://localhost:9096/
          predicates:
            - Path=/users/states
            - Method=GET
          filters:
            - PrefixPath=/user

        # 修改密码、重置密码  无token
        - id: resetPassword
          uri: http://localhost:9096/
          predicates:
              - Path=/users/password,/users/password/reset
              - Method=PUT
          filters:
              - PrefixPath=/user

        # 注册、登录 无token
        - id: register
          uri: http://localhost:9096/
          predicates:
            - Path=/users,/users/login
            - Method=POST
          filters:
            - PrefixPath=/user

        # 平台管理员获取所有用户列表 转发到权限网关
        - id: getUser
          uri: http://localhost:10001/
          predicates:
            - Path=/users/all,/users/{id}
            - Method=GET



      # 收藏模块
        - id: favorite
          uri: http://localhost:9093/
          predicates:
            - Path=/favorites,/favorites/goods/{skuId},/favorites/{id}
          filters:
            - PrefixPath=/favorite
            - Auth=authorization

      # 广告模块 无token
        - id: advertise
          uri: http://localhost:9097/
          predicates:
            - Path=/advertisement/states
          filters:
            - PrefixPath=/advertise


        # 获取当前时段广告列表 无token
        - id: getAdvertise
          uri: http://localhost:9097/
          predicates:
            - Path=/advertisement/current
          filters:
            - PrefixPath=/advertise

      # 售后模块
        - id: aftersaleState
          uri: http://localhost:9091/
          predicates:
            - Path=/aftersales/states
            - Method=GET
          filters:
            - PrefixPath=/aftersale

        - id: aftersale
          uri: http://localhost:9091/
          predicates:
            - Path=/orderItems/{id}/aftersales,/aftersales,/aftersales/{id},/aftersales/{id}/confirm,/aftersales/{id}/sendback
          filters:
            - PrefixPath=/aftersale
            - Auth=authorization




      # 地址服务
        - id: address
          uri: http://localhost:9090/
          predicates:
            - Path=/addresses,/addresses/{id},/addresses/{id},/region/{id}/ancestor
          filters:
            - PrefixPath=/address
            - Auth=authorization
      # 购物车
        - id: cart
          uri: http://localhost:9092/
          predicates:
            - Path=/carts,/carts/{id}
          filters:
            - PrefixPath=/cart
            - Auth=authorization
      # 分享模块
        - id: share
          uri: http://localhost:9095/
          predicates:
            - Path=/skus/{id}/shares,/shares,/beshared,/shareactivities
          filters:
            - PrefixPath=/share
            - Auth=authorization

      # 订单模块路由
        - id: order
          uri: http://localhost:10201/
          predicates:
            - Path=/orders,/orders/{id},/orders/{id}/**
          filters:
            - PrefixPath=/order
            - Auth=authorization
        - id: orderState
          uri: http://localhost:10201/
          predicates:
              - Path=/orders/states
          filters:
              - PrefixPath=/order

        # 运费服务
        - id: freight
          uri: http://localhost:9201/
          predicates:
            - Path=/region/{rid}/price
          filters:
            - PrefixPath=/freight
            - Auth=authorization
      # 支付
        - id: payment
          uri: http://localhost:9201/
          predicates:
            - Path=/payments/patterns,/orders/{id}/payments,/aftersales/{id}/payments,/aftersales/{id}/refunds,/orders/{id}/refunds
          filters:
            - PrefixPath=/payment
            - Auth=authorization
        # 支付状态 无token
        - id: paymentState
          uri: http://localhost:9201/
          predicates:
            - Path=/payments/states
          filters:
            - PrefixPath=/payment

      # 商品模块路由
      # 获取商品SPU的所有状态 无token
        - id: skus
          uri: http://localhost:9201/
          predicates:
            - Path=/skus/states,/skus,/skus/{id},/categories/{id}/subcategories,/spus/{id},/brands
            - Method=GET
          filters:
            - PrefixPath=/goods
      # 秒杀模块
        # 查看当前时段秒杀 无token
        - id: getflashsale
          uri: http://localhost:9201/
          predicates:
            - Path= /timesegments/{id}/flashsales,/flashsales/current
            - Method=GET
          filters:
            - PrefixPath=/flashsale
      # 评论模块
        # 获取评论状态 无Token
        - id: getComment
          uri: http://localhost:9201/
          predicates:
            - Path= /comments/states,/skus/{id}/comments
            - Method=GET
          filters:
            - PrefixPath=/comment

        - id: comment
          uri: http://localhost:9201/
          predicates:
            - Path= /orderitems/{id}/comments,/comments
          filters:
            - PrefixPath=/comment
            - Auth=authorization
      # 优惠服务
        - id: coupon
          uri: http://localhost:9201/
          predicates:
            - Path= /coupons,/couponactivities/{id}/usercoupons
          filters:
            - PrefixPath=/coupon
            - Auth=authorization
        # 优惠服务状态 无token
        - id: coupon
          uri: http://localhost:9201/
          predicates:
            - Path= /coupons/states
          filters:
            - PrefixPath=/coupon

        # 查看上线的优惠活动列表 无token
        - id: getcoupon
          uri: http://localhost:9201/
          predicates:
            - Path= /couponactivities,/couponactivities/{id}/skus
          filters:
            - PrefixPath=/coupon
      # 预售
        # 获得状态 无token
        - id: getpresale
          uri: http://localhost:9201/
          predicates:
              - Path= /presales/states,/presales
              - Method=GET
          filters:
              - PrefixPath=/presale
      # 团购
        - id: groupon
          uri: http://localhost:9201/
          predicates:
            - Path= /groupons
          filters:
            - PrefixPath=/groupon
            - Auth=authorization
        # 团购状态 无token
        - id: groupon
          uri: http://localhost:9201/
          predicates:
            - Path= /groupons/states
          filters:
            - PrefixPath=/groupon

  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    password: 123456
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000


management:
  endpoint:
    gateway:
      enabled: true

# 配置rocketmq
rocketmq:
  # 指定namesrv地址
  name-server: 47.115.162.144:9876
  producer:
    #生产者group名称
    group: producer_group
    #一次发送多少数量消息
    max-message-size: 4096
    #发送消息超时时间,默认3000
    send-message-timeout: 3000
    #发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 2

# 网关token相关配置
oomallgateway:
  jwtExpire: 3600
  refreshJwtTime: 60