
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: dbuser
    password: 123456
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
  redis:
    # Redis服务器地址
    host: 192.168.0.108
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    password:

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848