
spring:
  boot:
    admin:
      client:
        url: http://172.16.4.108:8081
        # url: http://localhost:8081
  datasource:
    url: jdbc:mysql://172.16.0.95:3306/oomall?serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8
    username: dbuser
    password: 123456
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

  cloud:
    nacos:
      discovery:
        #server-addr: 47.75.67.96:8848
        server-addr: 172.16.4.54:8848