package cn.edu.xmu.freight.mapper;

import cn.edu.xmu.freight.model.po.FreightPo;
import cn.edu.xmu.freight.model.po.FreightPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FreightPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    long countByExample(FreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    int deleteByExample(FreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    int insert(FreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    int insertSelective(FreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    List<FreightPo> selectByExample(FreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    FreightPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FreightPo record, @Param("example") FreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FreightPo record, @Param("example") FreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FreightPo record);
}