package cn.edu.xmu.freight.mapper;

import cn.edu.xmu.freight.model.po.PieceFreightPo;
import cn.edu.xmu.freight.model.po.PieceFreightPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PieceFreightPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    long countByExample(PieceFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int deleteByExample(PieceFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int insert(PieceFreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int insertSelective(PieceFreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    List<PieceFreightPo> selectByExample(PieceFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    PieceFreightPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PieceFreightPo record, @Param("example") PieceFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PieceFreightPo record, @Param("example") PieceFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PieceFreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table piece_freight_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PieceFreightPo record);
}