package cn.edu.xmu.freight.mapper;

import cn.edu.xmu.freight.model.po.WeightFreightPo;
import cn.edu.xmu.freight.model.po.WeightFreightPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeightFreightPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    long countByExample(WeightFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int deleteByExample(WeightFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int insert(WeightFreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int insertSelective(WeightFreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    List<WeightFreightPo> selectByExample(WeightFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    WeightFreightPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WeightFreightPo record, @Param("example") WeightFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WeightFreightPo record, @Param("example") WeightFreightPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WeightFreightPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight_freight_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WeightFreightPo record);
}